[package]
name = "writer"
version = "0.1.0"
edition = "2021"
authors = ["JavaharlalNehru <javaharlalnehru@yandex.ru>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]