[package]
edition = '2018'
build = '../common/build/build.rs'
name = 'validator_session'
version = '0.0.1'

[dependencies]
# domestic
catchain = { path = '../catchain' }
ever-crypto = { git = 'https://github.com/tonlabs/ever-labs-crypto', tag = '0.1.29' }
storage = { path = '../storage' }
ton_api = { git = 'https://github.com/tonlabs/ton-labs-tl', package = 'ton_api', tag = '0.2.129' }
ton_block = { git = 'https://github.com/tonlabs/ton-labs-block', tag = '1.8.0' }
ton_types = { git = 'https://github.com/tonlabs/ton-labs-types', tag = '1.11.3' }

# external
backtrace = '0.3'
crc = '3.0'
crossbeam = '0.7'
failure = '0.1'
hex = '0.4'
lazy_static = '1.4'
log = '0.4'
metrics-core = '0.5'
metrics-runtime = '0.13'
rand = '0.8'
sha2 = '0.9'
